# Generated by Django 5.2.15 on 2026-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_parkingevent_vehicle_x_vehicle_y"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("DETECTED", "Detected"),
                    ("SCANNED", "Scanned"),
                    ("WARNING_ISSUED", "Warning Issued"),
                ],
                db_index=True,
                default="DETECTED",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="parkingevent",
            name="zone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not", "주차구역 아님"),
                    ("NORMAL", "일반 주차구역 (흰색 선)"),
                    ("COMPACT", "경차 전용 (파란 선)"),
                    ("DISABLED", "장애인 전용 (파란 선 + 휠체어 표시)"),
                    ("EV", "전기차 전용 (초록 선)"),
                    ("FIRE", "소방차 전용 (주황색)"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
