# Generated by Django 5.2.15 on 2026-08-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_parkingevent_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("DETECTED", "Detected"),
                    ("SCANNED", "Scanned"),
                    ("WARNING_ISSUED", "Warning Issued"),
                    ("CLEARED", "Cleared"),
                    ("UNREACHABLE", "Unreachable"),
                ],
                db_index=True,
                default="DETECTED",
                max_length=15,
            ),
        ),
    ]
