# Generated by Django 5.2.15 on 2026-08-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_parkingevent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingevent",
            name="observation_yaw",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
